### PR TITLE
Remove duplicates in get_ssm_by_* using distinct

### PR DESCRIPTION
**Pull request by vladimirsouza**
See [this](https://morinlabsfu.slack.com/archives/C0224H120CU/p1708622853908019) Slack thread.

### CODE REVIEW

**Comment by Kdreval** [comment]
I think there was some other place where distinct was called, maybe get_ssm_by_sample(s)? We need to add this update there, too

**Comment by vladimirsouza** [comment]
```
### using changes of the last (second) commit in this PR.
maf_gamblrData_kostia <- get_ssm_by_regions(
  these_samples_metadata = filter(sample_data$meta, pathology == "BL"), 
  regions_bed = GAMBLR.data::grch37_ashm_regions %>% filter(gene == "MYC"),
  projection = "grch37",
  streamlined = FALSE,
  basic_columns = FALSE,
  this_seq_type = "genome"
)

### same code as above, but using the changes in the first commit of this PR.
maf_gamblrData_vlad <- ...

maf_gamblrData_kostia[maf_gamblrData_kostia == ""] <- NA
identical(maf_gamblrData_vlad, maf_gamblrData_kostia)
[1] TRUE
```
With the second commit, the code is simpler but reaches the same output.

**Comment by Kdreval** [comment]
Here
https://github.com/morinlab/GAMBLR.data/blob/f1d46ba8cb09ad73c102ce8391e39e507f909e56/R/get_ssm_by_samples.R#L102

**Comment by vladimirsouza** [comment]
502 more rows were filtered out from the get_ssm_by_samples output :)

**Review by Kdreval — APPROVED** [review]

**Pull request merged**
