### PR TITLE
Add support for return of all colours in legacy format

### PR DESCRIPTION
**Pull request by Kdreval**
The produced output of the `GAMBLR.data::get_colours(legacy_mode = TRUE)` is now replicating the output of the `get_gambl_colours()` functionality

### CODE REVIEW

**Comment by mattssca** [comment]
Thanks for the updates Kostia. Do we want to update the docs for the updated dataset as well? In addition, I don't think I can find the source of how this resource was compiled in the DATASET.R script. Maybe this (and my first comment) can wait, but we should create an issue of this for tracking purposes. What do you think?

**Comment by Kdreval** [comment]
I'm going to push the script to generate the sample_data, but the description seems to be concise and not having a place to describe the new CN column?
```
#' Sample Data
#'
#' Sample data bunlded as a list of 3 elements. Metadata (data frame) and sample data from two projections (grch37 and hg38),
#' Each projection is organized as a list of 3 elements; maf, seg, and bedpe (all data frames).
#'
#' @format ## `sample_data`
#' A list of three elements. 
#' Two elements are lists with three data frames in each list and the last element (metadata) is a data frame.
#' \describe{
#'   \item{meta}{A data frame with metadata.}
#'   \item{grch37}{A list containing 3 data frames; maf, seg, and bedpe. All in respect to grch37.}
#'   \item{hg38}{A list containing 3 data frames; maf, seg, and bedpe. All in respect to hg38.}
#' }
"sample_data"
```

**Comment by mattssca** [comment]
> I'm going to push the script to generate the sample_data, but the description seems to be concise and not having a place to describe the new CN column?
> 
> ```
> #' Sample Data
> #'
> #' Sample data bunlded as a list of 3 elements. Metadata (data frame) and sample data from two projections (grch37 and hg38),
> #' Each projection is organized as a list of 3 elements; maf, seg, and bedpe (all data frames).
> #'
> #' @format ## `sample_data`
> #' A list of three elements. 
> #' Two elements are lists with three data frames in each list and the last element (metadata) is a data frame.
> #' \describe{
> #'   \item{meta}{A data frame with metadata.}
> #'   \item{grch37}{A list containing 3 data frames; maf, seg, and bedpe. All in respect to grch37.}
> #'   \item{hg38}{A list containing 3 data frames; maf, seg, and bedpe. All in respect to hg38.}
> #' }
> "sample_data"
> ```

Yes, I am aware of this. We will rewrite the documentation for this bundled data at a later step since this is a behemoth of a dataset. Each element in the list would have to be documented, then we will add the new CN column. 

EDIT:  In addition, the newly added pathology_rank column in the metadata is also to be added in the docs. See [this](https://github.com/morinlab/GAMBLR.data/issues/21) issue.

**Comment by Kdreval** [comment]
Thanks for confirming! I agree documenting this can be tackled after all the separation is done. Just didn't want to overlook if there is another place I might have missed!

**Review by mattssca — APPROVED** [review]
Thanks for the updates, this PR is hereby approved for merge.

**Pull request merged**
